# Generated by Django 5.1.7 on 2025-03-27 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
