# Generated by Django 5.1.7 on 2025-03-26 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
